/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NatureRouteImport } from './routes/nature'
import { Route as IndexRouteImport } from './routes/index'

const NatureRoute = NatureRouteImport.update({
  id: '/nature',
  path: '/nature',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/nature': typeof NatureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/nature': typeof NatureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/nature': typeof NatureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/nature'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/nature'
  id: '__root__' | '/' | '/nature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NatureRoute: typeof NatureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nature': {
      id: '/nature'
      path: '/nature'
      fullPath: '/nature'
      preLoaderRoute: typeof NatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NatureRoute: NatureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
